# Generated by Django 4.1.7 on 2023-03-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseresult',
            name='delivery_time_orig',
            field=models.CharField(default='', max_length=20, verbose_name='Срок поставки (исх.дата)'),
        ),
        migrations.AlterField(
            model_name='parseresult',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Cтоимость,$'),
        ),
    ]
