# Generated by Django 4.1.7 on 2023-03-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_parseresult_delivery_time_orig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseresult',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='Просрочка проекта'),
        ),
    ]
