# Generated by Django 4.1.7 on 2023-03-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_parseresult_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parseresult',
            old_name='price',
            new_name='price_usd',
        ),
        migrations.AddField(
            model_name='parseresult',
            name='price_rur',
            field=models.PositiveIntegerField(default=0, verbose_name='Cтоимость,руб'),
        ),
    ]
